### ISSUE TITLE
Fix 'flow check' issues

### ISSUE THREAD

**Issue by joshyhargreaves** [joshyhargreaves/react-native-event-calendar#1]
Running 'yarn flow' in repository root yields a tonne of errors. 
Find and fix the cause of issues. 
![screen shot 2017-06-09 at 12 15 08 pm](https://user-images.githubusercontent.com/1807207/26973337-ee703d20-4d0d-11e7-8b7f-63ea4bc036b8.png)

**Comment by sibelius** [comment]
these are on react native core

**Comment by joshyhargreaves** [comment]
I suspect it's an issue with the flowconfig!

**Comment by sibelius** [comment]
You can just ignore all the node_modules

[ignore]
.*/node_modules/.*

and use flow-typed to provide some types
