### ISSUE TITLE
error VitualizedList module.

### ISSUE THREAD

**Issue by hungdev** [joshyhargreaves/react-native-event-calendar#2]
hi.
i create my project by using react-native init.
then i copy your src foder code to my demo project and run. but it says error.
how do i fix it?
could you export api ?
thank you.

<img width="408" alt="screen shot 2017-09-06 at 10 28 09 am" src="https://user-images.githubusercontent.com/12009276/30093223-218c3ed6-92ee-11e7-8ab2-0b04484b23c1.png">

**Comment by hungdev** [comment]
OOpppssss!! sorry !! everything is working perfectly! i didnt remove expo

**Comment by joshyhargreaves** [comment]
Great! :)
