### ISSUE TITLE
Willing contribute from forked repo

### ISSUE THREAD

**Issue by RetroSGJacobs** [joshyhargreaves/react-native-event-calendar#9]
Hello

I've been using this package for the project I am working on, but have needed some features that it does not have (some that have been brought up as issues). I have added these in my own fork of this, without any breaking changes from what I can tell. I would very much like to share these additions to this repo.

Additions include:
- Setting ref to EventCalendar to call methods (onRef prop)
- Ability to set header to upper case (upperCaseHeader prop)
- Callback for tapping / swiping to change date (dateChanged prop)
- Specify start and end times to show part of a day (start & end props)
- Override previous / next button icons by specifying own element (headerIconLeft & headerIconRight props)
- Method call to go to a specified date (_goToDate method)
- Override event background color by specifying the color attribute in the event object

You can view the updated readme.md here: https://github.com/RetroSGJacobs/react-native-event-calendar

**Comment by sibelius** [comment]
Please open PRs for this

**Comment by RetroSGJacobs** [comment]
Opened #10. As stated I can look at breaking down into multiple PRs if necessary.
